name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * WED


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Create and Activate Conda Env
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: councils-in-action
        environment-file: environment.yml

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # Install Tex Deps
    - run: |
        apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic

    # Build webpage
    - name: Build webpage
      shell: bash -l {0}
      run: |
        just build

    # Store PDF as Artifact
    - uses: actions/upload-artifact@v3
      with:
        name: councils-in-action-build
        path: _build/index.pdf
      
    # Publish to GH Pages
    - name: Publish Book
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _build/